### ISSUE TITLE
Portfolio Shortcode display issues

### ISSUE THREAD

**Issue by angela-crist** [UpThemes/freefolio#5]
This issue was originally here:  https://github.com/UpThemes/creative-theme/issues/67

@chriswallace said:
It seems our portfolio shortcode design is a bit weird. Some clearing issues and the tags/types display is a bit awkward as well.

https://www.evernote.com/shard/s3/sh/f8ad7612-74b4-47fa-893b-7e3b0350468e/af405db32fe91e6134a4b5dcd1661950/deep/0/Portfolio-Shortcode-Example---Creative.png

@garand said:
I can't reproduce this on my local. It works fine, but I had to make sure that Jetpack was installed and activated, and also that custom content types were enabled.

@chriswallace Can you update Jetpack on the demo site to 3.3 and see if that fixes it?

**Comment by garand** [comment]
The shortcode was set to display 3 columns instead of 2. All fixed now.
