### ISSUE TITLE
Column issues 

### ISSUE THREAD

**Issue by angela-crist** [UpThemes/freefolio#6]
https://wordpress.org/support/topic/column-troubles-and-post?replies=1#post-6691003

Hi,
I would love to use your awsome freefolio for my client, but I've got some troubles (to note, theme is custom build on bootstrap 3.0)

1) if I set columns on 3, they are not in one row - see here
code: [portfolio columns=3]

2) when I click on some refernce - the thumbnail image is there twice, why so?
see here
which page/post template is used for displaying?

Thanks a lot
Karolina

https://wordpress.org/plugins/freefolio/

**Comment by garand** [comment]
@angela-crist Is this still an issue?

**Comment by angela-crist** [comment]
We can close this thanks for bringing it up.
